name: "Docker Lint"

on:
  workflow_call:  # This allows the workflow to be reusable
    inputs:
      dockerfile-path:
        description: "Path to the Dockerfile"
        required: false
        type: string
        default: "./Dockerfile"
jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3