name: "Kotlin Unit Tests"

on:
  workflow_call:
    inputs:
      gradle-subdirectory:
        description: "Path to the Gradle project, if not in the root"
        required: false
        type: string
        default: "."  # Assumes the Gradle project is in the root by default

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ${{ inputs.gradle-subdirectory }}/gradlew

      - name: Build and Test
        run: ${{ inputs.gradle-subdirectory }}/gradlew test

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ inputs.gradle-subdirectory }}/build/test-results/test